language: objective-c

osx_image: xcode9.2
xcode_sdk: iphonesimulator11.2

xcode_workspace: Example/PlainPing.xcworkspace
xcode_scheme: PlainPing-Example

before_install:
    - pod install --project-directory=Example

notifications:
  slack: naptics:0jvqNePbU1ycOfefKuHZ3A6o
  email: false

script: xcodebuild clean build test -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK CODE_SIGNING_REQUIRED=NO
